# Generated by Django 5.0.1 on 2024-01-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('product', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecycleArticles',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apishop.shopmodel',),
        ),
    ]
