# Generated by Django 5.0.1 on 2024-01-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0003_delete_recyclearticles_recycleshop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmodel',
            name='image',
        ),
    ]
