# Generated by Django 5.0.1 on 2024-01-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apishop', '0005_shopmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='detail',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
