# Generated by Django 5.0.1 on 2024-01-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='comment_com_content_e419f0_idx')],
            },
        ),
    ]
